#!/usr/bin/env ruby
# frozen_string_literal: true

lib_path = File.expand_path('../lib', __dir__)
$LOAD_PATH.unshift(lib_path) if !$LOAD_PATH.include?(lib_path)
require 'hammerhead/cli'

Signal.trap('INT') do
  warn("\n#{caller.join("\n")}: interrupted")
  exit(1)
end

begin
  Hammerhead::CLI.start
rescue Hammerhead::CLI::Error => err
  puts "ERROR: #{err.message}"
  exit 1
end
